// ui.js — Binding tra pannello HTML e stato strutturale STEP 4
import {statoDefault,clonaStato,calcolaDerivati,salvaStato,caricaStato,cancellaStato,esportaJSON,importaJSON} from './modello.js';
import {getCatalogo} from './catalogo.js';
let statoCorrente=statoDefault();const listeners=new Set();
export function getStato(){return clonaStato(statoCorrente)} export function setStato(n){statoCorrente=clonaStato(n);renderUI();notifica()} export function onStatoChange(cb){listeners.add(cb);return()=>listeners.delete(cb)} function notifica(){listeners.forEach(cb=>cb(getStato()))}
const val=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v};const chk=(id,v)=>{const e=document.getElementById(id);if(e)e.checked=!!v};
function renderCampate(){const c=document.getElementById('lista-campate');if(!c)return;c.innerHTML='';statoCorrente.campate.forEach((x,i)=>{const r=document.createElement('div');r.className='campata-row';r.innerHTML=`<span>Campata ${i+1}</span><input type="number" min="6" max="30" step="1" value="${x.interasse}" data-i="${i}" class="input-interasse"><span>m</span><button class="btn-small btn-rimuovi" data-i="${i}">×</button>`;c.appendChild(r)});c.querySelectorAll('.input-interasse').forEach(e=>e.addEventListener('input',()=>{const i=+e.dataset.i,v=parseFloat(e.value);if(Number.isFinite(v)){statoCorrente.campate[i].interasse=v;notifica();clearTimeout(e._t);e._t=setTimeout(()=>salvaStato(statoCorrente),400)}}));c.querySelectorAll('.btn-rimuovi').forEach(e=>e.addEventListener('click',()=>{if(statoCorrente.campate.length<=1)return;statoCorrente.campate.splice(+e.dataset.i,1);renderCampate();notifica();salvaStato(statoCorrente)}))}
function renderUI(){const g=statoCorrente.generale;val('p-luce',g.luce);val('p-altezzaPilastro',g.altezzaPilastro);val('p-pendenzaCopertura',g.pendenzaCopertura);chk('p-interpiano',g.interpiano);val('p-altezzaInterpiano',g.altezzaInterpiano);chk('p-carroponte',g.carroponte);val('p-portataCarroponte',g.portataCarroponte);renderCampate();const p=getCatalogo('pilastri').pilastri,t=getCatalogo('travi').travi,c=getCatalogo('copertura').tegoli,f=getCatalogo('pannelli').finiture;const fill=(id,a,sel,fn)=>{const e=document.getElementById(id);if(e)e.innerHTML=a.map(fn).join('')};fill('p-tipoPilastro',p,statoCorrente.pilastri.tipoId,x=>`<option value="${x.id}"${x.id===sel?' selected':''}>${x.nome} (${x.sezione.l}×${x.sezione.h})</option>`);fill('p-tipoTrave',t,statoCorrente.travi.tipoId,x=>`<option value="${x.id}"${x.id===sel?' selected':''}>${x.nome}</option>`);fill('p-tipoTegolo',c,statoCorrente.copertura.tegoloId,x=>`<option value="${x.id}"${x.id===sel?' selected':''}>${x.nome}</option>`);fill('p-finituraPannello',f,statoCorrente.pannelli.finitura,x=>`<option value="${x.id}"${x.id===sel?' selected':''}>${x.nome}</option>`);val('p-spessorePannello',statoCorrente.pannelli.spessore)}
export {renderUI};
export function inizializzaUI(){const num=(id,g,k)=>{const e=document.getElementById(id);if(!e)return;e.addEventListener('input',()=>{const v=parseFloat(e.value);if(!Number.isFinite(v))return;statoCorrente[g][k]=v;notifica();clearTimeout(e._t);e._t=setTimeout(()=>salvaStato(statoCorrente),400)});};const sel=(id,g,k)=>{const e=document.getElementById(id);if(!e)return;e.addEventListener('change',()=>{statoCorrente[g][k]=e.value;notifica();salvaStato(statoCorrente)})};const ck=(id,g,k)=>{const e=document.getElementById(id);if(!e)return;e.addEventListener('change',()=>{statoCorrente[g][k]=e.checked;notifica();salvaStato(statoCorrente)})};num('p-luce','generale','luce');num('p-altezzaPilastro','generale','altezzaPilastro');num('p-pendenzaCopertura','generale','pendenzaCopertura');num('p-altezzaInterpiano','generale','altezzaInterpiano');num('p-portataCarroponte','generale','portataCarroponte');num('p-spessorePannello','pannelli','spessore');ck('p-interpiano','generale','interpiano');ck('p-carroponte','generale','carroponte');sel('p-tipoPilastro','pilastri','tipoId');sel('p-tipoTrave','travi','tipoId');sel('p-tipoTegolo','copertura','tegoloId');sel('p-finituraPannello','pannelli','finitura');document.getElementById('btn-aggiungiCampata')?.addEventListener('click',()=>{statoCorrente.campate.push({id:Date.now(),interasse:15});renderCampate();notifica();salvaStato(statoCorrente)});document.getElementById('btn-salva')?.addEventListener('click',()=>{salvaStato(statoCorrente);mostraStatus('Stato salvato')});document.getElementById('btn-carica')?.addEventListener('click',()=>{const s=caricaStato();if(s){setStato(s);mostraStatus('Stato caricato')}else mostraStatus('Nessun salvataggio trovato')});document.getElementById('btn-reset')?.addEventListener('click',()=>{if(confirm('Ripristinare i valori di default?')){cancellaStato();setStato(statoDefault());mostraStatus('Reset completato')}});const s=caricaStato();if(s)statoCorrente=s;renderUI();notifica()}
export function aggiornaRisultati(stato){const d=calcolaDerivati(stato);const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('r-lunghezza',d.L.toFixed(2)+' m');set('r-superficie',d.superficieCoperta.toFixed(1)+' m²');set('r-volume',d.volumeTotale.toFixed(2)+' m³');set('r-peso',d.pesoStimato.toFixed(2)+' t');set('r-pilastri',d.numPilastri);const b=document.querySelector('#tabella-distinta tbody');if(b)b.innerHTML=d.distinta.map(r=>`<tr><td>${r.elemento}</td><td>${r.quantita}</td><td>${r.dimensioni}</td><td>${r.volume.toFixed(2)}</td><td>${r.peso.toFixed(2)}</td></tr>`).join('')}
export function mostraStatus(m){const e=document.getElementById('status');if(!e)return;e.textContent=m;clearTimeout(e._t);e._t=setTimeout(()=>e.textContent='Pronto',2500)}
export function esportaProgetto(){esportaJSON(statoCorrente)} export async function importaProgetto(){try{const s=await importaJSON();setStato(s);salvaStato(statoCorrente);mostraStatus('Progetto importato')}catch(e){mostraStatus('Errore importazione: '+e.message)}}