'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TYPE={PILASTRI:'Pilastri',TRAVI:'Travi',MENSOLE:'Mensole trave','MENSOLE SOLAIO':'Mensole solaio',SOLAI:'Solai',MURI:'Muri',FONDAZIONI:'Fondazioni',ALTRO:'CAD non classificato'};
const state={doc:null,file:null,entities:[],elements:[],bounds:null,filter:'ALL',mode:'2d',zoom:1,pan:{x:0,y:0},selected:null,scene:null,camera:null,renderer:null,controls:null,objects:new Map(),labels:[]};
function norm(v){return String(v??'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function P(x=0,y=0,z=0){return {x:num(x),y:num(y),z:num(z)}}
function attr(ins,tag){const a=(ins.attribs||[]).find(x=>norm(x.tag)===norm(tag));return String(a?.value??a?.text??'').trim()}
function tr(p,ins){const sx=num(ins.xScale,1)||1,sy=num(ins.yScale,1)||1,a=num(ins.rotation)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),x=num(p.x)*sx,y=num(p.y)*sy;return P(num(ins.position?.x)+x*c-y*s,num(ins.position?.y)+x*s+y*c,num(ins.position?.z)+num(p.z))}
function block(doc,name){return doc?.blocks?.[name]?.entities||[]}
function entitySegments(e,ins={}){const t=norm(e.type),out=[];
 if(t==='LINE'&&e.vertices?.length>=2)out.push([tr(P(e.vertices[0].x,e.vertices[0].y,e.vertices[0].z),ins),tr(P(e.vertices[1].x,e.vertices[1].y,e.vertices[1].z),ins)]);
 else if(t==='LWPOLYLINE'||t==='POLYLINE'){const v=e.vertices||[];for(let i=1;i<v.length;i++)out.push([tr(P(v[i-1].x,v[i-1].y),ins),tr(P(v[i].x,v[i].y),ins)]);if((e.shape||e.closed)&&v.length>2)out.push([tr(P(v[v.length-1].x,v[v.length-1].y),ins),tr(P(v[0].x,v[0].y),ins)]);}
 else if((t==='CIRCLE'||t==='ARC')&&e.center){const c=tr(P(e.center.x,e.center.y),ins),r=Math.abs(num(e.radius))*Math.max(Math.abs(num(ins.xScale,1)||1),Math.abs(num(ins.yScale,1)||1)),a0=num(e.startAngle)*Math.PI/180,a1=(e.endAngle==null?360:num(e.endAngle))*Math.PI/180,n=40;for(let i=1;i<=n;i++){const a=a0+(a1-a0)*i/n,b=a0+(a1-a0)*(i-1)/n;out.push([P(c.x+r*Math.cos(b),c.y+r*Math.sin(b)),P(c.x+r*Math.cos(a),c.y+r*Math.sin(a))])}}
 return out}
function allPoints(segs){return segs.flat()}
function bbox(ps){if(!ps.length)return null;const xs=ps.map(p=>p.x),ys=ps.map(p=>p.y);return {minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function dims(b){return b?{w:b.maxX-b.minX,d:b.maxY-b.minY}:null}
function polyInfo(e,ins){const t=norm(e.type);if(t!=='LWPOLYLINE'&&t!=='POLYLINE')return null;const v=e.vertices||[];if(v.length<3||!(e.shape||e.closed))return null;const pts=v.map(p=>tr(P(p.x,p.y),ins));let area=0;for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];area+=a.x*b.y-b.x*a.y}return {pts,area:Math.abs(area)/2,bb:bbox(pts)} }
function classify(layer,blockName){const s=norm(layer+' '+blockName);if(/PILAST|COLONN|COLUMN/.test(s))return 'PILASTRI';if(/MENSOLE[ _-]*SOLAIO|MENSOLA[ _-]*SOLAIO/.test(s))return 'MENSOLE SOLAIO';if(/MENSOLE?[ _-]*TRAV/.test(s))return 'MENSOLE';if(/SOLAIO|SLAB/.test(s))return 'SOLAI';if(/TRAVE|BEAM|GIRDER/.test(s))return 'TRAVI';if(/MURO|WALL|PARETE/.test(s))return 'MURI';if(/FOND|FOUND|FOOTING/.test(s))return 'FONDAZIONI';return null}
function infer(bb){if(!bb)return null;const w=bb.maxX-bb.minX,d=bb.maxY-bb.minY,max=Math.max(w,d),min=Math.min(w,d);if(max>5*min&&min<2)return 'TRAVI';if(w<2.0&&d<2.0&&w>.1&&d>.1)return 'PILASTRI';return null}
function makeElement(ins,doc){const be=block(doc,ins.name),physical=[];let segs=[];for(const e of be){segs.push(...entitySegments(e,ins));const pi=polyInfo(e,ins);if(pi)physical.push(pi)}const bb=bbox(allPoints(segs));let type=classify(ins.layer,ins.name)||infer(bb);if(!type)return null;physical.sort((a,b)=>a.area-b.area);let footprint=physical.find(p=>p.area>0.00001)?.pts||null;if(type==='PILASTRI'&&footprint){const fbb=bbox(footprint);if(fbb)return baseElement(ins,type,fbb,segs,footprint,doc)}return baseElement(ins,type,bb,segs,footprint,doc)}
function baseElement(ins,type,bb,segs,footprint,doc){let id=attr(ins,'ID')||attr(ins,'TAG');if(type==='MENSOLE SOLAIO'&&!id)id=attr(ins,'MT')||'MT';return {uid:crypto.randomUUID(),type,id,layer:String(ins.layer||''),block:String(ins.name||''),position:P(ins.position?.x,ins.position?.y,ins.position?.z),bbox:bb,size:dims(bb),segments:segs,footprint,rotation:num(ins.rotation),raw:ins,doc}}
function collect(doc,name){state.doc=doc;state.file=name;state.elements=[];state.selected=null;for(const e of doc.entities||[])if(norm(e.type)==='INSERT'){const el=makeElement(e,doc);if(el)state.elements.push(el)}state.bounds=computeBounds(doc);updateUI();draw2D();build3D();$('#dropzone').classList.add('hidden');$('#status2').textContent=`${state.elements.length} elementi strutturali riconosciuti`;status(`Letto ${name}: ${doc.entities?.length||0} entità CAD, ${state.elements.length} elementi strutturali riconosciuti.`)}
function computeBounds(doc){let ps=[];for(const e of doc.entities||[]){if(norm(e.type)==='INSERT'){for(const x of block(doc,e.name))ps.push(...allPoints(entitySegments(x,e)))}else{ps.push(...allPoints(entitySegments(e,{})));if(e.position)ps.push(P(e.position.x,e.position.y));if(e.startPoint)ps.push(P(e.startPoint.x,e.startPoint.y));if(e.center)ps.push(P(e.center.x,e.center.y))}}return bbox(ps)||{minX:0,maxX:100,minY:0,maxY:100}}
function count(t){return state.elements.filter(e=>e.type===t).length}
function updateUI(){ $('#fileName').textContent=state.file||'Nessun file';$('#nAll').textContent=state.elements.length;$('#nPil').textContent=count('PILASTRI');$('#nTr').textContent=count('TRAVI');$('#nM').textContent=count('MENSOLE');$('#nMT').textContent=count('MENSOLE SOLAIO');$('#nSol').textContent=count('SOLAI');$('#nMur').textContent=count('MURI');$('#nFon').textContent=count('FONDAZIONI');$('#nPilSide').textContent=count('PILASTRI');$('#nTrSide').textContent=count('TRAVI');$('#nMSide').textContent=count('MENSOLE');$('#nMTSide').textContent=count('MENSOLE SOLAIO');$('#nSolSide').textContent=count('SOLAI');$('#nMurSide').textContent=count('MURI');$('#nFonSide').textContent=count('FONDAZIONI'); const groups=new Map();for(const e of state.elements){const k=e.id||'(senza ID)';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(e)}const dups=[...groups.values()].filter(a=>a.length>1);$('#nDup').textContent=dups.length;$('#nDupSide').textContent=dups.length;$('#nMiss').textContent=state.elements.filter(e=>!e.id).length;$('#stats').innerHTML=`Entità: <b>${state.doc?.entities?.length||0}</b> · INSERT: <b>${state.elements.length}</b> · Blocchi: <b>${Object.keys(state.doc?.blocks||{}).length}</b> · Layer: <b>${Object.keys(state.doc?.layers||{}).length}</b>`;$('#schedule').innerHTML=[...groups.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([id,a])=>`<tr data-id="${esc(a[0].uid)}"><td>${esc(id)}</td><td>${TYPE[a[0].type]}</td><td>${a.length}</td><td>${a[0].size?`${a[0].size.w.toFixed(2)} × ${a[0].size.d.toFixed(2)}`:'—'}</td><td>${esc(a[0].layer)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nessun elemento riconosciuto</td></tr>';$$('#schedule tr[data-id]').forEach(r=>r.onclick=()=>select(state.elements.find(e=>e.uid===r.dataset.id)));$('#selected').innerHTML=state.selected?selectionHTML(state.selected):'<span class="muted">Seleziona un elemento in 2D o 3D.</span>' }
function selectionHTML(e){return `<b>${esc(e.id||'(senza ID)')}</b><div>${TYPE[e.type]}</div><div>Dimensioni CAD: ${e.size?e.size.w.toFixed(3)+' × '+e.size.d.toFixed(3):'—'}</div><div>Posizione: ${e.position.x.toFixed(3)}, ${e.position.y.toFixed(3)}</div><div>Layer: ${esc(e.layer)}</div><div>Blocco: ${esc(e.block)}</div>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function status(s,bad=false){$('#status').textContent=s;$('#statusDot').className=bad?'bad':'ok'}
function filtered(){return state.elements.filter(e=>state.filter==='ALL'||e.type===state.filter||(state.filter==='ANOM'&&!e.id))}
function mapPoint(p){const svg=$('#svg2d'),W=svg.clientWidth||900,H=svg.clientHeight||600,b=state.bounds,pad=45,s=Math.min((W-2*pad)/(b.maxX-b.minX||1),(H-2*pad)/(b.maxY-b.minY||1))*state.zoom;const ox=W/2-(b.minX+b.maxX)/2*s+state.pan.x,oy=H/2+(b.minY+b.maxY)/2*s+state.pan.y;return [ox+p.x*s,oy-p.y*s]}
function svg(tag,a={}){const x=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a).forEach(([k,v])=>x.setAttribute(k,v));return x}
function draw2D(){const s=$('#svg2d');while(s.firstChild)s.removeChild(s.firstChild);if(!state.bounds)return;s.append(svg('rect',{x:0,y:0,width:'100%',height:'100%',fill:'#eef1f4'}));for(const e of state.doc?.entities||[]){for(const seg of entitySegments(e,{})){const a=mapPoint(seg[0]),b=mapPoint(seg[1]);s.append(svg('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#73808c','stroke-width':.7,opacity:.55}))}if(/TEXT|MTEXT/.test(norm(e.type))){const p=mapPoint(P(e.startPoint?.x??e.position?.x,e.startPoint?.y??e.position?.y));const t=svg('text',{x:p[0],y:p[1],fill:'#52606d','font-size':Math.max(9,num(e.textHeight,2)*state.zoom*.65)});t.textContent=e.text||e.textString||'';s.append(t)}}for(const e of filtered()){const sel=e===state.selected,col=sel?'#ef1740':({PILASTRI:'#26333f',TRAVI:'#0d5e92',MENSOLE:'#d88916','MENSOLE SOLAIO':'#7b4bc4',SOLAI:'#2d8b72',MURI:'#7b8794',FONDAZIONI:'#59636c'}[e.type]||'#4e5964');if(e.footprint){const pts=e.footprint.map(mapPoint),d=pts.map(p=>p.join(',')).join(' '),poly=svg('polygon',{points:d,fill:col,opacity:.2,stroke:col,'stroke-width':sel?3:1.5});poly.dataset.uid=e.uid;s.append(poly)}else for(const q of e.segments){const a=mapPoint(q[0]),b=mapPoint(q[1]),l=svg('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:col,'stroke-width':sel?3:2.2,opacity:.85});l.dataset.uid=e.uid;s.append(l)}const p=mapPoint(e.position),t=svg('text',{x:p[0]+7,y:p[1]-7,fill:col,'font-size':12,'font-weight':'700'});t.textContent=e.id||TYPE[e.type];t.dataset.uid=e.uid;s.append(t)}s.querySelectorAll('[data-uid]').forEach(n=>n.addEventListener('click',ev=>{ev.stopPropagation();select(state.elements.find(e=>e.uid===n.dataset.uid))}))}
function select(e){state.selected=e||null;updateUI();draw2D();highlight3D()}
function material(c,opacity=1){return new THREE.MeshStandardMaterial({color:c,transparent:opacity<1,opacity,roughness:.68,metalness:.04})}
function cssColor(t){return {PILASTRI:0x666d73,TRAVI:0x2473a8,MENSOLE:0xe29422,'MENSOLE SOLAIO':0x8150c7,SOLAI:0x4caa8d,MURI:0x8c969f,FONDAZIONI:0x5d6670}[t]||0x7b8790}
function center(e){return P((e.bbox.minX+e.bbox.maxX)/2,(e.bbox.minY+e.bbox.maxY)/2,0)}
function beamGeometry(e){let longest=null,len=0;for(const q of e.segments){const l=Math.hypot(q[1].x-q[0].x,q[1].y-q[0].y);if(l>len){len=l;longest=q}}if(!longest)return {length:Math.max(e.size?.w||0,e.size?.d||0,.5),width:Math.min(e.size?.w||.5,e.size?.d||.5),angle:e.rotation*Math.PI/180,center:center(e)};const dx=longest[1].x-longest[0].x,dy=longest[1].y-longest[0].y;return {length:len,width:Math.max(.12,Math.min(e.size?.w||.5,e.size?.d||.5)),angle:Math.atan2(dy,dx),center:P((longest[0].x+longest[1].x)/2,(longest[0].y+longest[1].y)/2)}}
function addLabel(text,pos,color){const c=document.createElement('canvas'),ctx=c.getContext('2d');ctx.font='bold 42px Arial';const w=ctx.measureText(text).width+28;c.width=w;c.height=58;ctx.font='bold 42px Arial';ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,58);ctx.fillStyle=color;ctx.fillText(text,14,43);const tex=new THREE.CanvasTexture(c),sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));sp.scale.set(Math.max(1.1,w/58),1.1,1);sp.position.copy(pos);sp.userData.label=true;state.scene.add(sp);state.labels.push(sp)}
function build3D(){if(!window.THREE)return;const host=$('#viewport3d');if(state.renderer){state.renderer.dispose();host.innerHTML=''}state.scene=new THREE.Scene();state.scene.background=new THREE.Color(0xe7ebef);state.camera=new THREE.PerspectiveCamera(42,Math.max(1,host.clientWidth)/Math.max(1,host.clientHeight),.01,10000);state.renderer=new THREE.WebGLRenderer({antialias:true});state.renderer.setPixelRatio(Math.min(devicePixelRatio,2));state.renderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight));state.renderer.shadowMap.enabled=true;host.appendChild(state.renderer.domElement);state.objects.clear();state.labels=[];state.scene.add(new THREE.HemisphereLight(0xffffff,0x59636c,1.7));const dl=new THREE.DirectionalLight(0xffffff,1.6);dl.position.set(15,-12,20);dl.castShadow=true;state.scene.add(dl);state.scene.add(new THREE.GridHelper(100,100));const H=Math.max(.5,num($('#colHeight').value,3)),SH=Math.max(.05,num($('#slabH').value,.3));for(const e of state.elements){const m=material(cssColor(e.type),e.type==='SOLAI'?.5:1);let mesh=null,x=0,y=0,z=0;if(e.type==='PILASTRI'){mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.05,e.size.w),Math.max(.05,e.size.d),H),m);const c=center(e);x=c.x;y=c.y;z=H/2}else if(e.type==='TRAVI'){const g=beamGeometry(e);mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.05,g.length),Math.max(.12,g.width),.6),m);x=g.center.x;y=g.center.y;z=H-.3;mesh.rotation.z=g.angle}else if(e.type==='MENSOLE'){mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.08,e.size.w),Math.max(.08,e.size.d),.5),m);const c=center(e);x=c.x;y=c.y;z=H-.6-.25;mesh.rotation.z=e.rotation*Math.PI/180}else if(e.type==='MENSOLE SOLAIO'){mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.08,e.size.w),Math.max(.08,e.size.d),.3),m);const c=center(e);x=c.x;y=c.y;z=H-.15;mesh.rotation.z=e.rotation*Math.PI/180}else if(e.type==='SOLAI'){mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.1,e.size.w),Math.max(.1,e.size.d),SH),m);const c=center(e);x=c.x;y=c.y;z=H-SH/2}else if(e.type==='MURI'){mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.1,e.size.w),Math.max(.1,e.size.d),H),m);const c=center(e);x=c.x;y=c.y;z=H/2}else if(e.type==='FONDAZIONI'){mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.1,e.size.w),Math.max(.1,e.size.d),.5),m);const c=center(e);x=c.x;y=c.y;z=.25}if(!mesh)continue;mesh.position.set(x,y,z);mesh.userData.uid=e.uid;mesh.castShadow=true;mesh.receiveShadow=true;state.scene.add(mesh);state.objects.set(e.uid,mesh);if(e.id)addLabel(e.id,new THREE.Vector3(x,y,z+(e.type==='PILASTRI'?H+.2:.7)),({PILASTRI:'#26333f',TRAVI:'#0d5e92',MENSOLE:'#b96d00','MENSOLE SOLAIO':'#6b3ea5',SOLAI:'#1f6d59'}[e.type]||'#44515c'))}state.controls=new THREE.OrbitControls(state.camera,state.renderer.domElement);state.controls.enableDamping=true;state.controls.dampingFactor=.08;fit3D();state.renderer.domElement.addEventListener('click',pick3D);animate()}
function fit3D(){if(!state.scene||!state.camera)return;const arr=[...state.objects.values()];if(!arr.length)return;const b=new THREE.Box3();arr.forEach(o=>b.expandByObject(o));const c=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()),m=Math.max(s.x,s.y,s.z,1);state.camera.position.set(c.x+m*1.7,c.y-m*1.7,c.z+m*1.2);state.controls?.target.copy(c);state.controls?.update()}
function pick3D(ev){const r=state.renderer.domElement.getBoundingClientRect(),p=new THREE.Vector2(((ev.clientX-r.left)/r.width)*2-1,-((ev.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(p,state.camera);const hits=ray.intersectObjects([...state.objects.values()],false);if(hits[0])select(state.elements.find(e=>e.uid===hits[0].object.userData.uid))}
function highlight3D(){state.objects.forEach((m,uid)=>{m.material.emissive.setHex(uid===state.selected?.uid?0x440000:0);m.material.emissiveIntensity=uid===state.selected?.uid?.5:0})}
function animate(){requestAnimationFrame(animate);if(state.renderer){state.controls?.update();state.renderer.render(state.scene,state.camera)}}
function switchMode(m){state.mode=m;$('#viewport2d').classList.toggle('hidden',m!=='2d');$('#viewport3d').classList.toggle('hidden',m!=='3d');$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));if(m==='3d')setTimeout(build3D,20)}
function reset2D(){state.zoom=1;state.pan={x:0,y:0};draw2D()}
function openFile(file){if(!/\.dxf$/i.test(file.name)){status('Questa versione accetta DXF ASCII (.dxf).',true);return}const r=new FileReader();r.onload=()=>{try{if(!window.DxfParser)throw Error('Parser DXF non disponibile');const doc=new DxfParser().parseSync(r.result);collect(doc,file.name)}catch(err){console.error(err);status('DXF non interpretabile: '+err.message,true);alert('Il file DXF non è stato interpretato. Può contenere entità/proxy non supportate dal parser browser.')}};r.readAsText(file)}
$('#fileInput').onchange=e=>{if(e.target.files[0])openFile(e.target.files[0])};$('#choose').onclick=()=>$('#fileInput').click();['dragover','drop'].forEach(ev=>$('#dropzone').addEventListener(ev,e=>{e.preventDefault();if(ev==='drop'&&e.dataTransfer.files[0])openFile(e.dataTransfer.files[0])}));
$$('.cat').forEach(b=>b.onclick=()=>{state.filter=b.dataset.cat;$$('.cat').forEach(x=>x.classList.toggle('active',x===b));draw2D()});$$('.modeBtn').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));$('#v2dTop').onclick=()=>switchMode('2d');$('#v3dTop').onclick=()=>switchMode('3d');$('#fit2d').onclick=reset2D;$('#home3d').onclick=fit3D;$('#reset3d').onclick=()=>{state.controls?.reset();fit3D()};$('#zin3d').onclick=()=>{state.camera.position.multiplyScalar(.8)};$('#zout3d').onclick=()=>{state.camera.position.multiplyScalar(1.25)};$('#fit3d').onclick=fit3D;$('#full').onclick=()=>$('#viewport3d').requestFullscreen?.();$('#colHeight').oninput=()=>state.doc&&build3D();$('#slabH').oninput=()=>state.doc&&build3D();$('#export').onclick=()=>{const rows=[['ID','Tipo','Quantita','Larghezza','Profondita','Layer','Blocco','X','Y'],...state.elements.map(e=>[e.id,TYPE[e.type],1,e.size?.w??'',e.size?.d??'',e.layer,e.block,e.position.x,e.position.y])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='abaco-cacem.csv';a.click()};$('#print').onclick=()=>window.print();window.addEventListener('resize',()=>{draw2D();if(state.renderer){const h=$('#viewport3d');state.renderer.setSize(Math.max(1,h.clientWidth),Math.max(1,h.clientHeight));state.camera.aspect=Math.max(1,h.clientWidth)/Math.max(1,h.clientHeight);state.camera.updateProjectionMatrix()}});let drag=null;$('#svg2d').addEventListener('mousedown',e=>{if(e.target.closest('[data-uid]'))return;drag={x:e.clientX,y:e.clientY,px:state.pan.x,py:state.pan.y}});window.addEventListener('mouseup',()=>drag=null);window.addEventListener('mousemove',e=>{if(drag){state.pan.x=drag.px+e.clientX-drag.x;state.pan.y=drag.py+e.clientY-drag.y;draw2D()}});$('#svg2d').addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.05,Math.min(30,state.zoom*(e.deltaY<0?1.12:.89)));draw2D()},{passive:false});